### ISSUE TITLE
Why is there an arity limit when generating a stub?

### ISSUE THREAD

**Issue by spiegela** [chef/mixer#8]
I'm working on a mixing using inaka/sumo_db, and have a function with an arity of 6.  Digging a little bit, I found a couple of _magic number_ limits:

My primary question is: _"why is there a function arity limit of 5 here"_: https://github.com/chef/mixer/blob/master/src/mixer.erl#L162 

In addition, there's a 2nd limit here with another arity limit of 26, which seems much more realistic, but I'm still curious about the reason.
https://github.com/chef/mixer/blob/master/src/mixer.erl#L185

Thanks!

**Comment by spiegela** [comment]
@elbrujohalcon do you have any thoughts on this?

**Comment by elbrujohalcon** [comment]
@spiegela : no, I have no idea. I've been bitten by the same thing a couple of times already.

**Comment by seth** [comment]
In terms of those limits being magic numbers, I don't think there is any terrific reason. I bet we could easily up the lower limit. Want to give that a shot?

**Comment by seth** [comment]
Perhaps there's even a more elegant approach for building up the calls. But for now, if you are getting stuck because you have /6 functions, let's see if there's a quick fix to make it work for you.

**Comment by spiegela** [comment]
Ah.  I see how this works now.  It looks like it might be ok to just expand support up to 26 arguments (which seems like more than enough) -- that way all there's only one limit.  There doesn't appear to be any downside to allowing for a higher limit.

The [technical arity limit is 255](http://www.erlang.org/doc/efficiency_guide/advanced.html), so we _could_ implement a simple encoder to create the generated arguments, but that's probably overkill.

**Comment by spiegela** [comment]
Resolved by #9
